version: '3.7'
services:
  uniform-web-1:
    image: uniform-web-1
    container_name: uniform-web-1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
#    command: ['ng serve --host 0.0.0.0']
